baseURL = "https://drummond.nyc/"
title = "Owen's Math Portal"
theme = "hugotex"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[pagination]
  pagerSize = 100

[Params.author]
  name = "Owen Drummond"
  abstract = """
    I am a graduate mathematics student at Rutgers University New Brunswick.
    """

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[Params]
  darkmode = false
  twittercard = false
  opengraph = false
  description = "Owen Drummond's mathematics portal."